[package]
name = "wayland_compositor"
version = "0.1.0"
authors = [ "i509VCB <git@i509.me>" ]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
clap = { version = "3.0.0-beta.4", features = [ "derive" ] }
slog = "2.1.1"
slog-term = "2.8"
slog-async = "2.2"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"

directories = "3.0.2"
inotify = { version = "0.9.3", default-features = false }

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
default-features = false
features = [
    "slog-stdlog",
    "use_system_lib",
    "wayland_frontend",
    "backend_winit"
]

[dependencies.x11rb]
optional = true
version = "0.8"
default-features = false
features = [
    "composite"
]

[features]
default = [ "winit" ] # I would add xwayland here, since I use the JVM a lot. However until other stuff is in place, there is little to enabling xwayland.
winit = [ "smithay/backend_winit" ]
xwayland = [ "smithay/xwayland", "x11rb" ]
